package com.example.dispute.room.domain;

public enum PermissionScope {
    CASE_READ,
    ROOM_MESSAGE_READ,
    ROOM_MESSAGE_WRITE,
    INTAKE_PRIVATE_READ,
    INTAKE_PARTICIPATE,
    EVIDENCE_READ,
    EVIDENCE_SUBMIT,
    EVIDENCE_PRIVATE_READ,
    HEARING_READ,
    HEARING_PARTICIPATE,
    REVIEW_READ,
    REVIEW_DECIDE,
    OUTCOME_READ,
    NOTIFICATION_READ,
    AGENT_SESSION_READ,
    AGENT_SESSION_WRITE
}
