package com.example.dispute.casecore.infrastructure;

import com.example.dispute.casecore.application.ExternalDisputeSimulationClient;
import com.example.dispute.casecore.application.SimulateExternalImportCommand;
import com.example.dispute.casecore.application.SimulatedExternalDispute;
import com.example.dispute.common.api.ErrorCode;
import com.example.dispute.common.exception.AgentExecutionException;
import com.example.dispute.common.trace.TraceIdFilter;
import com.example.dispute.config.ActorRole;
import com.example.dispute.domain.model.RiskLevel;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestClient;

/**
 * Legacy adapter retained for wire-contract compatibility tests.
 *
 * <p>It is intentionally not a Spring bean: simulated imports are generated by the Java
 * template catalog and never call the Python agent service.
 */
@Deprecated(forRemoval = false)
public class RestClientExternalDisputeSimulationClient
        implements ExternalDisputeSimulationClient {

    private static final String ENDPOINT = "/internal/agents/external-import/simulate";

    private final RestClient restClient;

    public RestClientExternalDisputeSimulationClient(
            @Qualifier("agentRestClient") RestClient restClient) {
        this.restClient = restClient;
    }

    @Override
    public List<SimulatedExternalDispute> simulate(
            SimulateExternalImportCommand command,
            String traceId,
            String requestId) {
        SimulationResponse response =
                restClient
                        .post()
                        .uri(ENDPOINT)
                        .header(TraceIdFilter.TRACE_HEADER, traceId)
                        .header(TraceIdFilter.REQUEST_HEADER, requestId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .body(AgentSimulationRequest.from(command))
                        .retrieve()
                        .body(SimulationResponse.class);
        int itemCount =
                response == null || response.items() == null
                        ? 0
                        : response.items().size();
        if (itemCount != 1) {
            throw new AgentExecutionException(
                    ErrorCode.AGENT_OUTPUT_SCHEMA_INVALID,
                    "external import simulator must return exactly one item",
                    Map.of("endpoint", ENDPOINT, "item_count", itemCount));
        }
        try {
            return response.items().stream()
                    .map(AgentSimulatedExternalDispute::toDomain)
                    .toList();
        } catch (IllegalArgumentException invalidItem) {
            throw new AgentExecutionException(
                    ErrorCode.AGENT_OUTPUT_SCHEMA_INVALID,
                    "external import simulator returned an invalid item",
                    Map.of(
                            "endpoint",
                            ENDPOINT,
                            "validation_error",
                            invalidItem.getMessage()));
        }
    }

    private record AgentSimulationRequest(
            @JsonProperty("count") int count,
            @JsonProperty("scenario") String scenario,
            @JsonProperty("risk_level_hint") RiskLevel riskLevelHint,
            @JsonProperty("initiator_role_hint") ActorRole initiatorRoleHint,
            @JsonProperty("current_actor_id") String currentActorId,
            @JsonProperty("counterparty_actor_id") String counterpartyActorId,
            @JsonProperty("simulation_batch_id") String simulationBatchId) {

        static AgentSimulationRequest from(SimulateExternalImportCommand command) {
            return new AgentSimulationRequest(
                    command.count(),
                    command.scenario(),
                    command.riskLevelHint(),
                    command.initiatorRoleHint(),
                    command.currentActorId(),
                    command.counterpartyActorId(),
                    command.simulationBatchId());
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    private record AgentSimulatedExternalDispute(
            @JsonProperty("source_system") String sourceSystem,
            @JsonProperty("external_case_reference") String externalCaseReference,
            @JsonProperty("order_reference") String orderReference,
            @JsonProperty("after_sales_reference") String afterSalesReference,
            @JsonProperty("logistics_reference") String logisticsReference,
            @JsonProperty("user_id") String userId,
            @JsonProperty("merchant_id") String merchantId,
            @JsonProperty("initiator_role") String initiatorRole,
            @JsonProperty("dispute_type") String disputeType,
            @JsonProperty("title") String title,
            @JsonProperty("description") String description,
            @JsonProperty("risk_level") RiskLevel riskLevel) {

        SimulatedExternalDispute toDomain() {
            return new SimulatedExternalDispute(
                    sourceSystem,
                    externalCaseReference,
                    orderReference,
                    afterSalesReference,
                    logisticsReference,
                    userId,
                    merchantId,
                    initiatorRole,
                    disputeType,
                    title,
                    description,
                    riskLevel);
        }
    }

    private record SimulationResponse(List<AgentSimulatedExternalDispute> items) {}
}
