/*
 * 所属模块：案件核心与导入。
 * 文件职责：把Rest外部争议模拟请求适配为受超时和协议校验约束的外部 HTTP 调用。
 * 业务链路：核心入口/契约为 「simulate」；维护争议案件事实、来源、幂等导入和演示数据清理。
 * 关键边界：Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
 */
package com.example.dispute.casecore.infrastructure;

import com.example.dispute.casecore.application.ExternalDisputeSimulationClient;
import com.example.dispute.casecore.application.SimulateExternalImportCommand;
import com.example.dispute.casecore.application.SimulatedExternalDispute;
import com.example.dispute.common.api.ErrorCode;
import com.example.dispute.common.exception.AgentExecutionException;
import com.example.dispute.common.trace.TraceIdFilter;
import com.example.dispute.config.ActorRole;
import com.example.dispute.domain.model.RiskLevel;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestClient;

/**
 * Legacy adapter retained for wire-contract compatibility tests.
 *
 * <p>It is intentionally not a Spring bean: simulated imports are generated by the Java
 * template catalog and never call the Python agent service.
 */
// 所属模块：【案件核心与导入 / 外部集成层】类型「RestClientExternalDisputeSimulationClient」。
// 类型职责：把Rest外部争议模拟请求适配为受超时和协议校验约束的外部 HTTP 调用；本类型显式提供 「RestClientExternalDisputeSimulationClient」、「simulate」。
// 协作关系：主要由 「RestClientExternalDisputeSimulationClientTest.rejectsAOneItemResponseWhosePartyIdentityViolatesTheSimulationContract」、「RestClientExternalDisputeSimulationClientTest.rejectsPythonAgentResponsesThatContainMoreThanOneItem」、「RestClientExternalDisputeSimulationClientTest.sendsAndReadsPythonAgentContractInSnakeCase」 使用。
// 边界意义：Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
// Java 语法：class 同时封装状态与方法；final 依赖通过构造器注入后不可重新指向。
@Deprecated(forRemoval = false)
public class RestClientExternalDisputeSimulationClient
        implements ExternalDisputeSimulationClient {

    private static final String ENDPOINT = "/internal/agents/external-import/simulate";

    private final RestClient restClient;

    // 所属模块：【案件核心与导入 / 外部集成层】「RestClientExternalDisputeSimulationClient.RestClientExternalDisputeSimulationClient(RestClient)」。
    // 具体功能：「RestClientExternalDisputeSimulationClient.RestClientExternalDisputeSimulationClient(RestClient)」：使用 「restClient」(RestClient) 初始化「RestClientExternalDisputeSimulationClient」的不可变状态或协作参数，使后续方法不必依赖半初始化对象。
    // 上游调用：「RestClientExternalDisputeSimulationClient.RestClientExternalDisputeSimulationClient(RestClient)」的上游创建点包括 「RestClientExternalDisputeSimulationClientTest.sendsAndReadsPythonAgentContractInSnakeCase」、「RestClientExternalDisputeSimulationClientTest.rejectsPythonAgentResponsesThatContainMoreThanOneItem」、「RestClientExternalDisputeSimulationClientTest.rejectsAOneItemResponseWhosePartyIdentityViolatesTheSimulationContract」。
    // 下游影响：「RestClientExternalDisputeSimulationClient.RestClientExternalDisputeSimulationClient(RestClient)」只产生当前对象的返回值或字段变化，不访问额外基础设施。
    // 系统意义：「RestClientExternalDisputeSimulationClient.RestClientExternalDisputeSimulationClient(RestClient)」负责主链路中的“Rest客户端外部争议模拟客户端”；Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
    // Java 语法：构造器名称与类名相同且没有返回类型；参数通常由 Spring 按类型注入。
    public RestClientExternalDisputeSimulationClient(
            @Qualifier("agentRestClient") RestClient restClient) {
        this.restClient = restClient;
    }

    // 所属模块：【案件核心与导入 / 外部集成层】「RestClientExternalDisputeSimulationClient.simulate(SimulateExternalImportCommand,String,String)」。
    // 具体功能：「RestClientExternalDisputeSimulationClient.simulate(SimulateExternalImportCommand,String,String)」：模拟列表：先调用受配置和超时控制的内部 HTTP 服务；实际协作者为 「restClient.post」、「AgentSimulationRequest.from」、「response.items」、「retrieve」；不满足前置条件时抛出 「AgentExecutionException」；处理的关键状态/协议值包括 「endpoint」、「item_count」、「validation_error」，最终返回「List<SimulatedExternalDispute>」。
    // 上游调用：「RestClientExternalDisputeSimulationClient.simulate(SimulateExternalImportCommand,String,String)」由使用「RestClientExternalDisputeSimulationClient」的控制器、应用服务、Workflow Activity 或测试场景触发。
    // 下游影响：「RestClientExternalDisputeSimulationClient.simulate(SimulateExternalImportCommand,String,String)」向下依次触达 「restClient.post」、「AgentSimulationRequest.from」、「response.items」、「retrieve」；计算结果以「List<SimulatedExternalDispute>」交给调用方。
    // 系统意义：「RestClientExternalDisputeSimulationClient.simulate(SimulateExternalImportCommand,String,String)」负责主链路中的“列表”；Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
    @Override
    public List<SimulatedExternalDispute> simulate(
            SimulateExternalImportCommand command,
            String traceId,
            String requestId) {
        SimulationResponse response =
                restClient
                        .post()
                        .uri(ENDPOINT)
                        .header(TraceIdFilter.TRACE_HEADER, traceId)
                        .header(TraceIdFilter.REQUEST_HEADER, requestId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .body(AgentSimulationRequest.from(command))
                        .retrieve()
                        .body(SimulationResponse.class);
        int itemCount =
                response == null || response.items() == null
                        ? 0
                        : response.items().size();
        if (itemCount != 1) {
            throw new AgentExecutionException(
                    ErrorCode.AGENT_OUTPUT_SCHEMA_INVALID,
                    "external import simulator must return exactly one item",
                    Map.of("endpoint", ENDPOINT, "item_count", itemCount));
        }
        try {
            return response.items().stream()
                    .map(AgentSimulatedExternalDispute::toDomain)
                    .toList();
        } catch (IllegalArgumentException invalidItem) {
            throw new AgentExecutionException(
                    ErrorCode.AGENT_OUTPUT_SCHEMA_INVALID,
                    "external import simulator returned an invalid item",
                    Map.of(
                            "endpoint",
                            ENDPOINT,
                            "validation_error",
                            invalidItem.getMessage()));
        }
    }

    // 所属模块：【案件核心与导入 / 外部集成层】类型「AgentSimulationRequest」。
    // 类型职责：定义Agent模拟跨层传递时使用的不可变数据契约；本类型显式提供 「from」。
    // 协作关系：主要由 「RestClientExternalDisputeSimulationClient.simulate」 使用。
    // 边界意义：Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
    // Java 语法：record 用于不可变数据载体，编译器会生成组件访问器和值语义方法。
    private record AgentSimulationRequest(
            @JsonProperty("count") int count,
            @JsonProperty("scenario") String scenario,
            @JsonProperty("risk_level_hint") RiskLevel riskLevelHint,
            @JsonProperty("initiator_role_hint") ActorRole initiatorRoleHint,
            @JsonProperty("current_actor_id") String currentActorId,
            @JsonProperty("counterparty_actor_id") String counterpartyActorId,
            @JsonProperty("simulation_batch_id") String simulationBatchId) {

        // 所属模块：【案件核心与导入 / 外部集成层】「RestClientExternalDisputeSimulationClient.AgentSimulationRequest.from(SimulateExternalImportCommand)」。
        // 具体功能：「RestClientExternalDisputeSimulationClient.AgentSimulationRequest.from(SimulateExternalImportCommand)」：转换Agent模拟；实际协作者为 「command.count」、「command.scenario」、「command.riskLevelHint」、「command.initiatorRoleHint」，最终返回「AgentSimulationRequest」。
        // 上游调用：「RestClientExternalDisputeSimulationClient.AgentSimulationRequest.from(SimulateExternalImportCommand)」的上游调用点包括 「RestClientExternalDisputeSimulationClient.simulate」。
        // 下游影响：「RestClientExternalDisputeSimulationClient.AgentSimulationRequest.from(SimulateExternalImportCommand)」向下依次触达 「command.count」、「command.scenario」、「command.riskLevelHint」、「command.initiatorRoleHint」；计算结果以「AgentSimulationRequest」交给调用方。
        // 系统意义：「RestClientExternalDisputeSimulationClient.AgentSimulationRequest.from(SimulateExternalImportCommand)」在对象进入事务、消息或 Temporal history 前拒绝非法值，可避免错误数据在异步链路中延迟爆炸。
        // Java 语法：record 自动生成组件访问器、equals、hashCode 和 toString，适合传递不可变业务快照。
        static AgentSimulationRequest from(SimulateExternalImportCommand command) {
            return new AgentSimulationRequest(
                    command.count(),
                    command.scenario(),
                    command.riskLevelHint(),
                    command.initiatorRoleHint(),
                    command.currentActorId(),
                    command.counterpartyActorId(),
                    command.simulationBatchId());
        }
    }

    // 所属模块：【案件核心与导入 / 外部集成层】类型「AgentSimulatedExternalDispute」。
    // 类型职责：定义Agent模拟外部争议跨层传递时使用的不可变数据契约；本类型显式提供 「toDomain」。
    // 协作关系：由同模块控制器、应用服务或框架生命周期创建和调用。
    // 边界意义：Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
    // Java 语法：record 用于不可变数据载体，编译器会生成组件访问器和值语义方法。
    @JsonIgnoreProperties(ignoreUnknown = true)
    private record AgentSimulatedExternalDispute(
            @JsonProperty("source_system") String sourceSystem,
            @JsonProperty("external_case_reference") String externalCaseReference,
            @JsonProperty("order_reference") String orderReference,
            @JsonProperty("after_sales_reference") String afterSalesReference,
            @JsonProperty("logistics_reference") String logisticsReference,
            @JsonProperty("user_id") String userId,
            @JsonProperty("merchant_id") String merchantId,
            @JsonProperty("initiator_role") String initiatorRole,
            @JsonProperty("dispute_type") String disputeType,
            @JsonProperty("title") String title,
            @JsonProperty("description") String description,
            @JsonProperty("risk_level") RiskLevel riskLevel) {

        // 所属模块：【案件核心与导入 / 外部集成层】「RestClientExternalDisputeSimulationClient.AgentSimulatedExternalDispute.toDomain()」。
        // 具体功能：「RestClientExternalDisputeSimulationClient.AgentSimulatedExternalDispute.toDomain()」：转换领域对象，最终返回「SimulatedExternalDispute」。
        // 上游调用：「RestClientExternalDisputeSimulationClient.AgentSimulatedExternalDispute.toDomain()」由使用「AgentSimulatedExternalDispute」的控制器、应用服务、Workflow Activity 或测试场景触发。
        // 下游影响：「RestClientExternalDisputeSimulationClient.AgentSimulatedExternalDispute.toDomain()」只产生当前对象的返回值或字段变化，不访问额外基础设施；计算结果以「SimulatedExternalDispute」交给调用方。
        // 系统意义：「RestClientExternalDisputeSimulationClient.AgentSimulatedExternalDispute.toDomain()」统一“领域对象”的跨层表示，避免不同入口产生不兼容字段；Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
        // Java 语法：record 自动生成组件访问器、equals、hashCode 和 toString，适合传递不可变业务快照。
        SimulatedExternalDispute toDomain() {
            return new SimulatedExternalDispute(
                    sourceSystem,
                    externalCaseReference,
                    orderReference,
                    afterSalesReference,
                    logisticsReference,
                    userId,
                    merchantId,
                    initiatorRole,
                    disputeType,
                    title,
                    description,
                    riskLevel);
        }
    }

    // 所属模块：【案件核心与导入 / 外部集成层】类型「SimulationResponse」。
    // 类型职责：定义模拟响应跨层传递时使用的不可变数据契约；本类型显式提供 框架生成的默认访问器。
    // 协作关系：由同模块控制器、应用服务或框架生命周期创建和调用。
    // 边界意义：Java/PostgreSQL 是案件状态事实源，导入重试不能创建重复案件
    // Java 语法：record 用于不可变数据载体，编译器会生成组件访问器和值语义方法。
    private record SimulationResponse(List<AgentSimulatedExternalDispute> items) {}
}
