package com.example.dispute.domain.model;

public enum CaseStatus {
    INTAKE_PENDING,
    INTAKE_IN_PROGRESS,
    NOT_ADMISSIBLE,
    WAITING_SLOT_COMPLETION,
    INTAKE_COMPLETED,
    EVIDENCE_OPEN,
    EVIDENCE_SEALED,
    DOSSIER_BUILDING,
    DOSSIER_BUILT,
    ROUTED,
    HEARING,
    HEARING_OPEN,
    WAITING_EVIDENCE,
    SETTLEMENT_PENDING,
    DRAFT_READY,
    DELIBERATION_RUNNING,
    REVIEW_PENDING,
    REMEDY_PLANNED,
    WAITING_HUMAN_REVIEW,
    MANUAL_HANDOFF,
    APPROVED_FOR_EXECUTION,
    EXECUTING,
    CLOSED,
    CANCELLED
}
