package com.example.dispute.notification.domain;

public enum NotificationType {
    INTAKE_ACCEPTED,
    DISPUTE_SUMMONS,
    EVIDENCE_ROOM_OPENED,
    EVIDENCE_DEADLINE_WARNING,
    HEARING_OPENED,
    SUPPLEMENT_REQUESTED,
    SETTLEMENT_CONFIRMATION_REQUIRED,
    REVIEW_PENDING,
    FINAL_DECISION,
    EXECUTION_COMPLETED,
    MANUAL_HANDOFF
}
