package com.example.dispute.workflow.temporal.caseprocess;

import com.example.dispute.workflow.contract.v1.ContractTypes.RoomType;
import com.example.dispute.workflow.temporal.caseprocess.CaseProcessCarryState.ActiveChildKind;
import com.example.dispute.workflow.temporal.caseprocess.CaseProcessCarryState.RecoveryErrorOrigin;
import java.util.List;

public record CaseProcessSnapshot(
    String schemaVersion,
    String workflowId,
    String workflowRunId,
    String tenantSurrogate,
    String caseId,
    String macroPhase,
    RoomType activeRoomType,
    long activeRoomEpoch,
    String activeChildWorkflowId,
    long observedProcessRevision,
    long nextCommandSequence,
    long nextCaseEventSequence,
    long processedCommandCount,
    long processedEventCount,
    int pendingCommandCount,
    int bufferedEventCount,
    int recentCommandCount,
    long highestObservedCommandSequence,
    long highestObservedEventSequence,
    int runGeneration,
    String blockedReason,
    String protocolErrorCode,
    List<String> recentCommandIds,
    long activeFencingToken,
    String activeChildWorkflowRunId,
    int provisioningCommitmentCount,
    String activeProvisioningSha256,
    ActiveChildKind activeChildKind,
    String activeSelectionSchemaVersion,
    String activeRoomWorkflowType,
    String activeRoomWorkflowBuildId,
    Long activeRoomRevision,
    RecoveryErrorOrigin protocolErrorOrigin,
    boolean provisioningManualRecoveryRequired) {

  public CaseProcessSnapshot(
      String schemaVersion,
      String workflowId,
      String workflowRunId,
      String tenantSurrogate,
      String caseId,
      String macroPhase,
      RoomType activeRoomType,
      long activeRoomEpoch,
      String activeChildWorkflowId,
      long observedProcessRevision,
      long nextCommandSequence,
      long nextCaseEventSequence,
      long processedCommandCount,
      long processedEventCount,
      int pendingCommandCount,
      int bufferedEventCount,
      int recentCommandCount,
      long highestObservedCommandSequence,
      long highestObservedEventSequence,
      int runGeneration,
      String blockedReason,
      String protocolErrorCode,
      List<String> recentCommandIds) {
    this(
        schemaVersion,
        workflowId,
        workflowRunId,
        tenantSurrogate,
        caseId,
        macroPhase,
        activeRoomType,
        activeRoomEpoch,
        activeChildWorkflowId,
        observedProcessRevision,
        nextCommandSequence,
        nextCaseEventSequence,
        processedCommandCount,
        processedEventCount,
        pendingCommandCount,
        bufferedEventCount,
        recentCommandCount,
        highestObservedCommandSequence,
        highestObservedEventSequence,
        runGeneration,
        blockedReason,
        protocolErrorCode,
        recentCommandIds,
        0,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        false);
  }

  public CaseProcessSnapshot(
      String schemaVersion,
      String workflowId,
      String workflowRunId,
      String tenantSurrogate,
      String caseId,
      String macroPhase,
      RoomType activeRoomType,
      long activeRoomEpoch,
      String activeChildWorkflowId,
      long observedProcessRevision,
      long nextCommandSequence,
      long nextCaseEventSequence,
      long processedCommandCount,
      long processedEventCount,
      int pendingCommandCount,
      int bufferedEventCount,
      int recentCommandCount,
      long highestObservedCommandSequence,
      long highestObservedEventSequence,
      int runGeneration,
      String blockedReason,
      String protocolErrorCode,
      List<String> recentCommandIds,
      long activeFencingToken,
      String activeChildWorkflowRunId,
      int provisioningCommitmentCount,
      String activeProvisioningSha256) {
    this(
        schemaVersion,
        workflowId,
        workflowRunId,
        tenantSurrogate,
        caseId,
        macroPhase,
        activeRoomType,
        activeRoomEpoch,
        activeChildWorkflowId,
        observedProcessRevision,
        nextCommandSequence,
        nextCaseEventSequence,
        processedCommandCount,
        processedEventCount,
        pendingCommandCount,
        bufferedEventCount,
        recentCommandCount,
        highestObservedCommandSequence,
        highestObservedEventSequence,
        runGeneration,
        blockedReason,
        protocolErrorCode,
        recentCommandIds,
        activeFencingToken,
        activeChildWorkflowRunId,
        provisioningCommitmentCount,
        activeProvisioningSha256,
        null,
        null,
        null,
        null,
        null,
        null,
        false);
  }

  public CaseProcessSnapshot(
      String schemaVersion,
      String workflowId,
      String workflowRunId,
      String tenantSurrogate,
      String caseId,
      String macroPhase,
      RoomType activeRoomType,
      long activeRoomEpoch,
      String activeChildWorkflowId,
      long observedProcessRevision,
      long nextCommandSequence,
      long nextCaseEventSequence,
      long processedCommandCount,
      long processedEventCount,
      int pendingCommandCount,
      int bufferedEventCount,
      int recentCommandCount,
      long highestObservedCommandSequence,
      long highestObservedEventSequence,
      int runGeneration,
      String blockedReason,
      String protocolErrorCode,
      List<String> recentCommandIds,
      long activeFencingToken,
      String activeChildWorkflowRunId,
      int provisioningCommitmentCount,
      String activeProvisioningSha256,
      ActiveChildKind activeChildKind,
      String activeSelectionSchemaVersion,
      String activeRoomWorkflowType,
      String activeRoomWorkflowBuildId) {
    this(
        schemaVersion,
        workflowId,
        workflowRunId,
        tenantSurrogate,
        caseId,
        macroPhase,
        activeRoomType,
        activeRoomEpoch,
        activeChildWorkflowId,
        observedProcessRevision,
        nextCommandSequence,
        nextCaseEventSequence,
        processedCommandCount,
        processedEventCount,
        pendingCommandCount,
        bufferedEventCount,
        recentCommandCount,
        highestObservedCommandSequence,
        highestObservedEventSequence,
        runGeneration,
        blockedReason,
        protocolErrorCode,
        recentCommandIds,
        activeFencingToken,
        activeChildWorkflowRunId,
        provisioningCommitmentCount,
        activeProvisioningSha256,
        activeChildKind,
        activeSelectionSchemaVersion,
        activeRoomWorkflowType,
        activeRoomWorkflowBuildId,
        null,
        null,
        false);
  }

  public CaseProcessSnapshot(
      String schemaVersion,
      String workflowId,
      String workflowRunId,
      String tenantSurrogate,
      String caseId,
      String macroPhase,
      RoomType activeRoomType,
      long activeRoomEpoch,
      String activeChildWorkflowId,
      long observedProcessRevision,
      long nextCommandSequence,
      long nextCaseEventSequence,
      long processedCommandCount,
      long processedEventCount,
      int pendingCommandCount,
      int bufferedEventCount,
      int recentCommandCount,
      long highestObservedCommandSequence,
      long highestObservedEventSequence,
      int runGeneration,
      String blockedReason,
      String protocolErrorCode,
      List<String> recentCommandIds,
      long activeFencingToken,
      String activeChildWorkflowRunId,
      int provisioningCommitmentCount,
      String activeProvisioningSha256,
      ActiveChildKind activeChildKind,
      String activeSelectionSchemaVersion,
      String activeRoomWorkflowType,
      String activeRoomWorkflowBuildId,
      Long activeRoomRevision,
      RecoveryErrorOrigin protocolErrorOrigin) {
    this(
        schemaVersion,
        workflowId,
        workflowRunId,
        tenantSurrogate,
        caseId,
        macroPhase,
        activeRoomType,
        activeRoomEpoch,
        activeChildWorkflowId,
        observedProcessRevision,
        nextCommandSequence,
        nextCaseEventSequence,
        processedCommandCount,
        processedEventCount,
        pendingCommandCount,
        bufferedEventCount,
        recentCommandCount,
        highestObservedCommandSequence,
        highestObservedEventSequence,
        runGeneration,
        blockedReason,
        protocolErrorCode,
        recentCommandIds,
        activeFencingToken,
        activeChildWorkflowRunId,
        provisioningCommitmentCount,
        activeProvisioningSha256,
        activeChildKind,
        activeSelectionSchemaVersion,
        activeRoomWorkflowType,
        activeRoomWorkflowBuildId,
        activeRoomRevision,
        protocolErrorOrigin,
        false);
  }

  public CaseProcessSnapshot {
    if (!"case-process-snapshot.v1".equals(schemaVersion)) {
      throw new IllegalArgumentException("schemaVersion must be case-process-snapshot.v1");
    }
    recentCommandIds = List.copyOf(recentCommandIds);
    if (activeFencingToken < 0
        || provisioningCommitmentCount < 0
        || (activeRoomRevision != null && activeRoomRevision < 0)) {
      throw new IllegalArgumentException("provisioning snapshot counters are invalid");
    }
  }
}
